sudo: false
language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.18"
    - "5.14"
matrix:
    fast_finish: true
before_install:
    - "cpanm -n List::Util"
    - "cpanm -n Scalar::Util"
    - "cpanm -n Time::Duration::Concise"
    - "cpanm -n Text::CSV"
script:
    - "perl Makefile.PL && make test"
