sudo: false
language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.18"
    - "5.14"
matrix:
    fast_finish: true
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -n Moose"
    - "cpanm -n List::Util"
    - "cpanm -n RedisDB"
    - "cpanm -n Date::Utility"
    - "cpanm -n Scalar::Util"
    - "cpanm -n Sereal::Encoder"
    - "cpanm -n Sereal::Decoder"
    - "cpanm -n Time::Duration::Concise"
    - "cpanm -n MooseX::Types::Moose"
    - "cpanm -n Test::RedisServer"
    - "cpanm -n Text::CSV"
script:
    - "perl Makefile.PL && make test"
    - "kill $(ps aux | grep 'redis' | awk '{print $2}')"
